import { test, expect } from "@playwright/test";
import { draftKey, publishedKey } from "../src/engine/content";

test("30 关筛选、复制、批量编排、迁移、删除、刷新及重新应用保持 ID 与进度", async ({ page }) => {
  await page.addInitScript(({ draft, published }) => {
    if (sessionStorage.getItem("scale-seeded")) return;
    sessionStorage.setItem("scale-seeded", "1");
    const chapters = [1, 2, 3].map((index) => ({ id: `chapter-${index}`, title: `第${index}章`, description: "", order: index - 1 }));
    const sections = [1, 2, 3, 4].map((index) => ({ id: `section-${index}`, chapterId: index < 3 ? "chapter-1" : index === 3 ? "chapter-2" : "chapter-3", title: `第${index}节`, description: "", order: index }));
    const levels = Array.from({ length: 30 }, (_, index) => ({ id: `scale-level-${String(index + 1).padStart(2, "0")}`, title: `规模关卡 ${String(index + 1).padStart(2, "0")}`, description: "", mode: index % 2 ? "3d" : "2d", radius: index % 2 ? 8 : 10, targetColors: "0".repeat(index % 2 ? 4913 : 441), revision: 1, source: "manual", archived: false }));
    const placements = levels.slice(0, 10).map((level, order) => ({ levelId: level.id, sectionId: "section-1", order }));
    const content = { format: "pixel-code-lab.content", version: 1, chapters, sections, levels, placements };
    localStorage.setItem(draft, JSON.stringify(content));
    localStorage.setItem(published, JSON.stringify(content));
    localStorage.setItem("pixel-code-lab.progress", JSON.stringify({ schemaVersion: 1, codes: { "scale-level-01": "def pixel(x, y):\n    return 0" }, passed: { "scale-level-01": true }, levelId: "scale-level-01", introSeen: true }));
  }, { draft: draftKey, published: publishedKey });
  await page.goto("/#/admin/levels");
  await expect(page.getByText("自定义 30 关")).toBeVisible();
  await page.getByRole("combobox", { name: "筛选维度" }).selectOption("3d");
  await expect(page.getByText("显示 22 关")).toBeVisible();
  await page.getByRole("combobox", { name: "筛选编排" }).selectOption("unplaced");
  await expect(page.getByText("显示 17 关")).toBeVisible();
  await page.getByRole("combobox", { name: "筛选维度" }).selectOption("all");
  await page.getByRole("combobox", { name: "筛选编排" }).selectOption("all");
  await page.getByRole("textbox", { name: "搜索关卡" }).fill("规模关卡 01");
  await expect(page.getByText("显示 1 关")).toBeVisible();
  await page.getByRole("button", { name: "复制关卡" }).click();
  const copiedId = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).levels.at(-1).id as string, draftKey);
  expect(copiedId).not.toBe("scale-level-01");
  await page.locator(".admin-list article").filter({ hasText: "scale-level-01" }).getByRole("button", { name: "归档" }).click();
  await expect(page.getByText(/影响 1 个关卡/)).toBeVisible();
  await page.getByRole("button", { name: "确认归档" }).click();
  await page.getByRole("combobox", { name: "筛选归档" }).selectOption("archived");
  await expect(page.getByText("显示 1 关")).toBeVisible();
  await page.getByRole("button", { name: "恢复" }).click();
  await page.getByRole("button", { name: "确认恢复" }).click();
  await page.getByRole("combobox", { name: "筛选归档" }).selectOption("all");
  await page.getByRole("textbox", { name: "搜索关卡" }).fill("");
  await page.getByRole("button", { name: "章节管理" }).click();
  await page.getByRole("button", { name: /第2节/ }).click();
  await page.getByRole("combobox", { name: "将第2节迁移到大章" }).selectOption("chapter-2");
  await expect(page.getByText(/涉及 0 个关卡/)).toBeVisible();
  await page.getByRole("button", { name: "确认迁移" }).click();
  await page.getByRole("button", { name: /第1节/ }).click();
  await page.getByRole("button", { name: "删除", exact: true }).click();
  await expect(page.getByText(/涉及 10 个关卡/)).toBeVisible();
  await page.getByRole("button", { name: "确认删除" }).click();
  await page.getByRole("button", { name: "撤回上一步" }).click();
  await page.getByRole("button", { name: /第1节/ }).click();
  await page.getByRole("button", { name: "归档", exact: true }).click();
  await expect(page.getByText(/涉及 10 个关卡/)).toBeVisible();
  await page.getByRole("button", { name: "确认操作" }).click();
  await page.getByRole("button", { name: "恢复", exact: true }).click();
  await page.getByRole("button", { name: "确认操作" }).click();
  await page.getByRole("button", { name: "关卡编排" }).click();
  await page.getByRole("button", { name: /第2节/ }).click();
  await page.getByRole("textbox", { name: "搜索关卡池" }).fill("规模关卡");
  await page.getByRole("button", { name: /全选当前结果/ }).click();
  await page.getByRole("button", { name: /批量加入/ }).click();
  await expect(page.getByRole("heading", { name: /第2节 · 当前关卡 \(21\)/ })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: "test-results/admin-scale-arrangement-wide.png" });
  await page.setViewportSize({ width: 1180, height: 768 });
  await page.screenshot({ path: "test-results/admin-scale-arrangement.png" });
  await page.getByRole("checkbox", { name: "选择当前 scale-level-11" }).check();
  await page.getByRole("checkbox", { name: "选择当前 scale-level-12" }).check();
  await page.getByRole("combobox", { name: "批量移动到小节" }).selectOption("section-3");
  await page.getByRole("button", { name: "批量移动 (2)" }).click();
  await expect(page.getByRole("heading", { name: /第2节 · 当前关卡 \(19\)/ })).toBeVisible();
  await page.getByRole("button", { name: "撤回上一步" }).click();
  await expect(page.getByRole("heading", { name: /第2节 · 当前关卡 \(21\)/ })).toBeVisible();
  await page.getByRole("button", { name: `上移 scale-level-30` }).click();
  await page.getByRole("combobox", { name: "移动 scale-level-30 到小节" }).selectOption("section-3");
  await page.getByRole("button", { name: "应用到本机挑战" }).click();
  await page.reload();
  const result = await page.evaluate(({ draft, published }) => ({ draft: JSON.parse(localStorage.getItem(draft)!), published: JSON.parse(localStorage.getItem(published)!), progress: JSON.parse(localStorage.getItem("pixel-code-lab.progress")!) }), { draft: draftKey, published: publishedKey });
  expect(result.draft.levels).toHaveLength(31);
  expect(result.draft.sections.find((item: { id: string }) => item.id === "section-2").chapterId).toBe("chapter-2");
  expect(result.draft.placements.find((item: { levelId: string }) => item.levelId === "scale-level-01").sectionId).toBe("section-1");
  expect(result.draft.placements.find((item: { levelId: string }) => item.levelId === "scale-level-30").sectionId).toBe("section-3");
  expect(result.published.placements).toEqual(result.draft.placements);
  expect(result.progress.passed["scale-level-01"]).toBe(true);
  expect(result.progress.passed[copiedId]).toBeUndefined();
  await page.getByRole("button", { name: "应用到本机挑战" }).click();
  await expect(page.getByText("本机挑战：与管理内容一致")).toBeVisible();
  await page.getByRole("button", { name: "返回学生入口" }).click();
  await page.getByRole("button", { name: /第1章/ }).click();
  await page.getByRole("button", { name: /第1节/ }).click();
  await expect(page.getByRole("button", { name: /规模关卡 01.*已通关/ })).toBeVisible();
});
