import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { parseProgress } from '../src/hooks/useProgress'
import { hitCell, initialView, zoomView } from '../src/engine/view'
import { evaluate, targetColors } from '../src/engine/evaluate'
import { levels } from '../src/engine/levels'

test('判定排除空白、严格计入多画漏画错色，边界正确', () => {
  expect(evaluate([0, 1, 0], [0, 1, 0])).toEqual({ passed: true, percent: 100 })
  expect(evaluate([0, 1, 0], [0, 0, 0]).percent).toBe(0)
  expect(evaluate([0, 1, 0], [5, 1, 0]).percent).toBe(50)
  expect(evaluate([1, 5], [1, 1]).percent).toBe(50)
  expect(evaluate([0], [7]).passed).toBe(false)
  expect(evaluate([0], [0]).percent).toBe(100)
  expect(evaluate(Array(2000).fill(1), [...Array(1999).fill(1), 0])).toEqual({ passed: false, percent: 99.9 })
  expect(() => evaluate([1], [9])).toThrow()
  expect(targetColors(levels[0]).filter(x => x === 1)).toHaveLength(25)
  expect(levels[1].target(-1, 0)).toBe(5)
  expect(levels[2].target(8, 0)).toBe(5)
  expect(levels[2].target(8, 1)).toBe(0)
})

test('真实 Python 三关通过，错误行号、返回值、隔离、历史作品', async ({ page }) => {
  const browserErrors: string[] = []
  page.on('pageerror', error => browserErrors.push(error.message))
  await openChallenge(page)
  const run = page.getByRole('button', { name: '运行', exact: true })
  await expect(run).toBeEnabled()
  await run.click()
  await expect(page.getByTestId('score')).toContainText('0.0%')
  await writeCode(page, 'def pixel(x, y):\n    return 1 if abs(x) <= 2 and abs(y) <= 2 else 0')
  await run.click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
  await expect(page.getByRole('button', { name: /实心正方形.*已通关/ })).toBeVisible()
  await page.screenshot({ path: 'test-results/square-passed.png', fullPage: true })
  await writeCode(page, 'def pixel(x, y):\n    return 1 / 0')
  await run.click()
  await expect(page.locator('.error[role=alert]')).toContainText('第 2 行')
  await expect(page.locator('.error[role=alert]')).toContainText('ZeroDivisionError')
  await expect(page.getByText('当前显示上次成功运行的结果，请以重新运行为准。')).toBeVisible()
  await writeCode(page, 'def pixel(x, y)\n    return 1')
  await run.click()
  await expect(page.locator('.error[role=alert]')).toContainText('SyntaxError · 第 1 行')
  for (const value of ['True', '1.0', 'None', '9']) {
    await writeCode(page, `def pixel(x, y):\n    return ${value}`)
    await run.click()
    await expect(page.locator('.error[role=alert]')).toContainText('InvalidColor')
  }
  await writeCode(page, 'message = "no function"')
  await run.click()
  await expect(page.locator('.error[role=alert]')).toContainText('MissingFunction')
  await page.getByRole('button', { name: /双色棋盘/ }).click()
  await writeCode(page, 'def pixel(x, y):\n    return 1 if (x+y)%2 == 0 else 5')
  await run.click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
  await page.getByRole('button', { name: /实心圆/ }).click()
  await writeCode(page, 'print("x" * 10000)\ndef pixel(x, y):\n    return 5 if x*x+y*y <= 64 else 0')
  await run.click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
  await expect(page.locator('pre')).toContainText('输出已截断')
  expect((await page.locator('pre').innerText()).length).toBeLessThan(4100)
  expect(browserErrors).toEqual([])
})

test('死循环超时、手动停止、切关取消后可继续运行', async ({ page }) => {
  await openChallenge(page)
  const run = page.getByRole('button', { name: '运行', exact: true })
  await expect(run).toBeEnabled()
  await writeCode(page, 'while True:\n    pass')
  await run.click()
  await expect(page.locator('.error[role=alert]')).toContainText('Timeout')
  await expect(run).toBeEnabled()
  await writeCode(page, 'def pixel(x, y):\n    while True:\n        pass')
  await run.click()
  await page.getByRole('button', { name: '停止', exact: true }).click()
  await expect(page.locator('.error[role=alert]')).toContainText('本次运行已停止')
  await expect(run).toBeEnabled()
  await run.click()
  await page.getByRole('button', { name: /双色棋盘/ }).click()
  await expect(run).toBeEnabled()
  await expect(page.locator('.error[role=alert]')).toHaveCount(0)
  await expect(page.getByTestId('score')).toHaveCount(0)
  await writeCode(page, 'def pixel(x, y):\n    return 1 if (x+y)%2 == 0 else 5')
  await run.click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
})

test('加载失败可重试', async ({ page }) => {
  await page.route('**/pyodide/pyodide.mjs', route => route.abort())
  await openChallenge(page)
  await expect(page.getByRole('button', { name: '重试加载' })).toBeVisible()
  await expect(page.getByRole('button', { name: '运行', exact: true })).toBeDisabled()
  await page.unroute('**/pyodide/pyodide.mjs')
  await page.getByRole('button', { name: '重试加载' }).click()
  await expect(page.getByRole('button', { name: '运行', exact: true })).toBeEnabled()
})


async function openChallenge(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: '开始挑战' }).click()
  await expect(page.locator('.monaco-editor .view-lines')).toBeVisible()
}
async function writeCode(page: Page, code: string) {
  const editor = page.locator('.code-editor')
  await editor.click({ position: { x: 160, y: 50 } })
  await page.keyboard.press('ControlOrMeta+A')
  await page.keyboard.insertText(code)
}

test('存档校验与缩放坐标计算', () => {
  expect(parseProgress(null).levelId).toBe('square')
  expect(() => parseProgress('{broken')).toThrow()
  expect(() => parseProgress(JSON.stringify({ schemaVersion: 2 }))).toThrow()
  expect(hitCell(300, 300, 5, initialView)).toEqual({ col: 5, row: 5, x: 0, y: 0 })
  const zoomed = zoomView(initialView, 2, 400, 300)
  expect(hitCell(400, 300, 5, zoomed)).toEqual(hitCell(400, 300, 5, initialView))
  expect(hitCell(0, 0, 5, initialView)).toBeNull()
})

test('首次说明、Monaco、本地进度、切关及刷新恢复、恢复模板', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '开始挑战' }).click()
  await expect(page.locator('.monaco-editor')).toBeVisible()
  const solution = 'def pixel(x, y):\n    return 1 if abs(x) <= 2 and abs(y) <= 2 else 0'
  await writeCode(page, solution)
  await expect(page.getByRole('button', { name: '运行', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '运行', exact: true }).click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
  await page.getByRole('button', { name: /双色棋盘/ }).click()
  await writeCode(page, 'def pixel(x, y):\n    return 5')
  // 在防抖窗口内切关，必须保存最新代码。
  await page.getByRole('button', { name: /实心圆/ }).click()
  await page.reload()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /实心圆/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: /实心正方形.*已通关/ })).toBeVisible()
  await page.getByRole('button', { name: /双色棋盘/ }).click()
  await expect(page.locator('.view-lines')).toContainText('return 5')
  await page.getByRole('button', { name: /实心正方形/ }).click()
  await expect(page.locator('.view-lines')).toContainText('abs(x)')
  await expect(page.getByTestId('score')).toHaveCount(0)
  await page.getByRole('button', { name: '使用说明' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '恢复初始代码' }).click()
  await expect(page.locator('.view-lines')).toContainText('abs(x)')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '恢复初始代码' }).click()
  await expect(page.locator('.view-lines')).toContainText('return 0')
  await expect(page.getByRole('button', { name: /实心正方形.*已通关/ })).toBeVisible()
  await expect(page.getByTestId('storage-status')).toContainText('已保存')
  await writeCode(page, 'def pixel(x, y):\n    return 8')
  await page.reload()
  await expect(page.locator('.view-lines')).toContainText('return 8')
})

test('两图联动缩放平移、坐标命中与重置', async ({ page }) => {
  await openChallenge(page)
  const target = page.getByLabel('目标图画布')
  const work = page.getByLabel('学生作品画布')
  await expect(target).toHaveAttribute('data-view', '1,0,0')
  await target.hover({ position: { x: 175, y: 175 } })
  await expect(page.locator('.coordinate').first()).toContainText('(0, 0) · 1 红')
  await page.mouse.wheel(0, -200)
  await expect(target).not.toHaveAttribute('data-view', '1,0,0')
  await expect.poll(async () => (await target.getAttribute('data-view')) === (await work.getAttribute('data-view'))).toBe(true)
  const before = await target.getAttribute('data-view')
  const box = (await work.boundingBox())!
  await work.scrollIntoViewIfNeeded()
  const visibleBox = (await work.boundingBox())!
  await page.mouse.move(visibleBox.x + box.width / 2, visibleBox.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(visibleBox.x + box.width / 2 + 40, visibleBox.y + box.height / 2 + 20, { steps: 5 })
  await page.mouse.up()
  await expect(work).not.toHaveAttribute('data-view', before!)
  await expect.poll(async () => (await target.getAttribute('data-view')) === (await work.getAttribute('data-view'))).toBe(true)
  await page.getByRole('button', { name: '重置视图' }).click()
  await expect(target).toHaveAttribute('data-view', '1,0,0')
  await expect(work).toHaveAttribute('data-view', '1,0,0')
  await target.hover({ position: { x: 2, y: 2 } })
  await expect(page.locator('.coordinate').first()).toContainText('画布范围外')
  await page.getByRole('button', { name: '放大视图' }).click()
  await page.getByRole('button', { name: /实心圆/ }).click()
  await expect(page.getByLabel('目标图画布')).toHaveAttribute('data-view', '1,0,0')
  await page.screenshot({ path: 'test-results/monaco-linked-canvas.png', fullPage: true })
})

test('损坏存档保留原文，确认后可恢复保存', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('pixel-code-lab.progress', '{broken'))
  await openChallenge(page)
  await expect(page.getByTestId('storage-status')).toContainText('原存档已保留')
  await writeCode(page, 'def pixel(x, y):\n    return 2')
  expect(await page.evaluate(() => localStorage.getItem('pixel-code-lab.progress'))).toBe('{broken')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '重试保存' }).click()
  await expect(page.getByTestId('storage-status')).toContainText('已保存')
  expect(JSON.parse((await page.evaluate(() => localStorage.getItem('pixel-code-lab.progress')))!).codes.square).toContain('return 2')
})

test('存储被禁用不会阻止写代码与运行', async ({ page }) => {
  await page.addInitScript(() => {
    const get = Storage.prototype.getItem
    const set = Storage.prototype.setItem
    Storage.prototype.getItem = function (key) { if (key === 'pixel-code-lab.progress') throw new DOMException('blocked', 'SecurityError'); return get.call(this, key) }
    Storage.prototype.setItem = function (key, value) { if (key === 'pixel-code-lab.progress') throw new DOMException('full', 'QuotaExceededError'); return set.call(this, key, value) }
  })
  await openChallenge(page)
  await expect(page.getByTestId('storage-status')).toContainText('保存失败')
  await writeCode(page, 'def pixel(x, y):\n    return 0')
  await expect(page.getByRole('button', { name: '运行', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '运行', exact: true }).click()
  await expect(page.getByTestId('score')).toContainText('0.0%')
})
