import { test, expect } from '@playwright/test'
import { evaluate, targetColors } from '../src/engine/evaluate'
import { levels } from '../src/engine/levels'

test('判定排除空白、严格计入多画漏画错色，边界正确', () => {
  expect(evaluate([0, 1, 0], [0, 1, 0])).toEqual({ passed: true, percent: 100 })
  expect(evaluate([0, 1, 0], [0, 0, 0]).percent).toBe(0)
  expect(evaluate([0, 1, 0], [5, 1, 0]).percent).toBe(50)
  expect(evaluate([1, 5], [1, 1]).percent).toBe(50)
  expect(evaluate([0], [7]).passed).toBe(false)
  expect(evaluate([0], [0]).percent).toBe(100)
  expect(evaluate(Array(2000).fill(1), [...Array(1999).fill(1), 0])).toEqual({ passed: false, percent: 99.9 })
  expect(() => evaluate([1], [9])).toThrow()
  expect(targetColors(levels[0]).filter(x => x === 1)).toHaveLength(25)
  expect(levels[1].target(-1, 0)).toBe(5)
  expect(levels[2].target(8, 0)).toBe(5)
  expect(levels[2].target(8, 1)).toBe(0)
})

test('真实 Python 三关通过，错误行号、返回值、隔离、历史作品', async ({ page }) => {
  const browserErrors: string[] = []
  page.on('pageerror', error => browserErrors.push(error.message))
  await page.goto('/')
  const input = page.getByRole('textbox', { name: 'Python代码' })
  const run = page.getByRole('button', { name: '运行', exact: true })
  await expect(run).toBeEnabled()
  await run.click()
  await expect(page.getByTestId('score')).toContainText('0.0%')
  await input.fill('def pixel(x, y):\n    return 1 if abs(x) <= 2 and abs(y) <= 2 else 0')
  await run.click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
  await expect(page.getByRole('button', { name: /实心正方形.*已通关/ })).toBeVisible()
  await page.screenshot({ path: 'test-results/square-passed.png', fullPage: true })
  await input.fill('def pixel(x, y):\n    return 1 / 0')
  await run.click()
  await expect(page.getByRole('alert')).toContainText('第 2 行')
  await expect(page.getByRole('alert')).toContainText('ZeroDivisionError')
  await expect(page.getByText('当前显示上次成功运行的结果，请以重新运行为准。')).toBeVisible()
  await input.fill('def pixel(x, y)\n    return 1')
  await run.click()
  await expect(page.getByRole('alert')).toContainText('SyntaxError · 第 1 行')
  for (const value of ['True', '1.0', 'None', '9']) {
    await input.fill(`def pixel(x, y):\n    return ${value}`)
    await run.click()
    await expect(page.getByRole('alert')).toContainText('InvalidColor')
  }
  await input.fill('message = "no function"')
  await run.click()
  await expect(page.getByRole('alert')).toContainText('MissingFunction')
  await page.getByRole('button', { name: /双色棋盘/ }).click()
  await input.fill('def pixel(x, y):\n    return 1 if (x+y)%2 == 0 else 5')
  await run.click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
  await page.getByRole('button', { name: /实心圆/ }).click()
  await input.fill('print("x" * 10000)\ndef pixel(x, y):\n    return 5 if x*x+y*y <= 64 else 0')
  await run.click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
  await expect(page.locator('pre')).toContainText('输出已截断')
  expect((await page.locator('pre').innerText()).length).toBeLessThan(4100)
  expect(browserErrors).toEqual([])
})

test('死循环超时、手动停止、切关取消后可继续运行', async ({ page }) => {
  await page.goto('/')
  const input = page.getByRole('textbox', { name: 'Python代码' })
  const run = page.getByRole('button', { name: '运行', exact: true })
  await expect(run).toBeEnabled()
  await input.fill('while True:\n    pass')
  await run.click()
  await expect(page.getByRole('alert')).toContainText('Timeout')
  await expect(run).toBeEnabled()
  await input.fill('def pixel(x, y):\n    while True:\n        pass')
  await run.click()
  await page.getByRole('button', { name: '停止', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('本次运行已停止')
  await expect(run).toBeEnabled()
  await run.click()
  await page.getByRole('button', { name: /双色棋盘/ }).click()
  await expect(run).toBeEnabled()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByTestId('score')).toHaveCount(0)
  await input.fill('def pixel(x, y):\n    return 1 if (x+y)%2 == 0 else 5')
  await run.click()
  await expect(page.getByTestId('score')).toContainText('100.0%')
})

test('加载失败可重试', async ({ page }) => {
  await page.route('**/pyodide/pyodide.mjs', route => route.abort())
  await page.goto('/')
  await expect(page.getByRole('button', { name: '重试加载' })).toBeVisible()
  await expect(page.getByRole('button', { name: '运行', exact: true })).toBeDisabled()
  await page.unroute('**/pyodide/pyodide.mjs')
  await page.getByRole('button', { name: '重试加载' }).click()
  await expect(page.getByRole('button', { name: '运行', exact: true })).toBeEnabled()
})
