import { test, expect } from '@playwright/test'

test('三维示例、视角、错误恢复、独立存档和模式取消', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.setViewportSize({ width: 1440, height: 900 })
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await page.getByRole('button', { name: '开始挑战', exact: true }).click()
  await page.getByRole('button', { name: '3D 体素', exact: true }).click()
  const run = page.getByRole('button', { name: '运行', exact: true })
  const canvas = page.getByLabel('三维体素画布')
  const write = async (source: string) => {
    await page.evaluate(code => navigator.clipboard.writeText(code), source)
    await page.locator('.code-editor').click({ position: { x: 160, y: 50 } })
    await page.keyboard.press('ControlOrMeta+A')
    await page.keyboard.press('ControlOrMeta+V')
  }
  await expect(run).toBeEnabled()
  await page.getByRole('button', { name: /立方体/ }).click(); await page.getByRole('button', { name: '载入示例', exact: true }).click()
  await run.click()
  await expect(canvas).toHaveAttribute('data-voxels', '343')
  await page.screenshot({ path: 'test-results/voxel-cube.png', fullPage: true })
  const before = await canvas.getAttribute('data-view')
  await canvas.hover()
  await page.mouse.down(); await page.mouse.move(1100, 500, { steps: 8 }); await page.mouse.up()
  await expect(canvas).not.toHaveAttribute('data-view', before!)
  await page.mouse.wheel(0, -200)
  await page.getByRole('button', { name: '重置视角' }).click()
  await expect(canvas).toHaveAttribute('data-view', before!)
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: /球体/ }).click(); await page.getByRole('button', { name: '载入示例', exact: true }).click()
  await run.click()
  await expect(canvas).toHaveAttribute('data-voxels', '925')
  await page.screenshot({ path: 'test-results/voxel-sphere.png', fullPage: true })
  await write('def voxel(x, y, z):\n    return 1 / 0')
  await run.click()
  await expect(page.locator('.error[role=alert]')).toContainText('第 2 行')
  await expect(canvas).toHaveAttribute('data-voxels', '925')
  for (const value of ['True', '1.0', 'None', '9']) {
    await write(`def voxel(x, y, z):\n    return ${value}`)
    await run.click()
    await expect(page.locator('.error[role=alert]')).toContainText('InvalidColor')
  }
  await write('def voxel(x, y, z):\n    return 4 if (x, y, z) == (1, 2, 3) else 0')
  await run.click()
  await expect(canvas).toHaveAttribute('data-voxels', '1')
  await page.getByRole('button', { name: '2D 像素挑战', exact: true }).click()
  await expect(page.locator('.view-lines')).toContainText('def pixel')
  await page.getByRole('button', { name: '3D 体素', exact: true }).click()
  await expect(page.locator('.view-lines')).toContainText('(1, 2, 3)')
  await page.reload()
  await expect(canvas).toBeVisible()
  await expect(page.locator('.view-lines')).toContainText('(1, 2, 3)')
  await expect(canvas).toHaveAttribute('data-voxels', '0')
  await expect(run).toBeEnabled()
  await write('while True:\n    pass')
  await run.click()
  await expect(page.locator('.error[role=alert]')).toContainText('Timeout')
  await expect(run).toBeEnabled()
  await run.click()
  await page.getByRole('button', { name: '停止', exact: true }).click()
  await expect(page.locator('.error[role=alert]')).toContainText('本次运行已停止')
  await expect(run).toBeEnabled()
  await run.click()
  await page.getByRole('button', { name: '2D 像素挑战', exact: true }).click()
  await expect(run).toBeEnabled()
  await run.click()
  await expect(page.getByTestId('score')).toContainText('0.0%')
  expect(errors).toEqual([])
})
